# Generated by Django 3.2.12 on 2022-10-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.IntegerField()),
                ('main_category', models.CharField(max_length=15)),
                ('sub_category', models.CharField(max_length=15)),
                ('detail', models.CharField(max_length=20)),
                ('DC', models.BooleanField(default=False)),
                ('fixed_expenses', models.BooleanField(default=False)),
            ],
        ),
    ]
