# Generated by Django 3.2.12 on 2022-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
